<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Admin | CodeSentinel</title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><script src="https://cdn.jsdelivr.net/npm/chart.js"></script><link href="${pageContext.request.contextPath}/static/css/style.css" rel="stylesheet"></head>
<body><nav class="topbar"><a class="brand" href="${pageContext.request.contextPath}/admin/dashboard"><span>Code</span>Sentinel Admin<span class="cursor"></span></a><div class="topbar-actions"><a class="btn btn-outline-light btn-sm" href="${pageContext.request.contextPath}/logout">Logout</a></div></nav>
<div class="app-frame"><aside class="sidebar"><a class="active" href="${pageContext.request.contextPath}/admin/dashboard">Dashboard</a><a href="${pageContext.request.contextPath}/admin/users">User Management</a><a href="${pageContext.request.contextPath}/admin/monitor">Code Monitor</a></aside>
<main class="content fade-in"><div class="page-head"><div><h1>Platform Analytics</h1><p>Security and activity overview.</p></div></div>
<section class="stat-grid"><div class="stat-card"><span>Total Users</span><strong>${totalUsers}</strong></div><div class="stat-card"><span>Active Users</span><strong>${activeUsers}</strong></div><div class="stat-card"><span>Total Submissions</span><strong>${totalSubmissions}</strong></div><div class="stat-card"><span>Total Bugs Detected</span><strong>${totalBugs}</strong></div></section>
<section class="stat-grid"><div class="stat-card"><span>Admins</span><strong>${roleSummary.ADMIN}</strong></div><div class="stat-card"><span>Developers</span><strong>${roleSummary.DEVELOPER}</strong></div><div class="stat-card"><span>High/Risky Reports</span><strong>${platformRisk.HIGH + platformRisk.CRITICAL}</strong></div><div class="stat-card"><span>Recent Submissions</span><strong>${highRiskSubmissions.size()}</strong></div></section>
<section class="chart-grid"><div class="panel"><h2>Last 7 Days Activity</h2><canvas id="activityChart" data-labels="${activityLabels}" data-values="${activityValues}"></canvas></div><div class="panel"><h2>Risk Distribution</h2><div class="risk-summary"><span><strong>${platformRisk.LOW}</strong> Low</span><span><strong>${platformRisk.MEDIUM}</strong> Medium</span><span><strong>${platformRisk.HIGH}</strong> High</span><span><strong>${platformRisk.CRITICAL}</strong> Critical</span></div></div></section>
<section class="panel"><h2>Recent High-Risk Submissions</h2><div class="table-responsive"><table class="table sentinel-table"><thead><tr><th>User</th><th>Title</th><th>Risk</th><th>Date</th><th>Action</th></tr></thead><tbody><c:forEach items="${highRiskSubmissions}" var="s"><tr><td>${s.user.email}</td><td>${s.title}</td><td><span class="risk ${s.report.riskLevel}">${s.report.riskLevel}</span></td><td>${s.submittedAt}</td><td><a class="link-info" href="${pageContext.request.contextPath}/report/${s.report.id}">View</a></td></tr></c:forEach><c:if test="${empty highRiskSubmissions}"><tr><td colspan="5" class="text-center muted">No high-risk submissions found.</td></tr></c:if></tbody></table></div></section>
<section class="panel"><h2>Recent Registrations</h2><table class="table sentinel-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Joined</th></tr></thead><tbody><c:forEach items="${recentUsers}" var="u"><tr><td>${u.fullName}</td><td>${u.email}</td><td>${u.role}</td><td>${u.createdAt}</td></tr></c:forEach></tbody></table></section>
</main></div><script src="${pageContext.request.contextPath}/static/js/app.js"></script></body></html>
